# $Id: Makefile,v 1.1 2001/07/11 00:23:35 pete Exp $

MAINTAINER=pete@bilogic.org

DOC?= article

FORMATS?= html

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"

